import 'package:flutter/material.dart';
import 'package:oxschool/presentation/components/custom_icon_button.dart';

class DisciplineHistoryGrid extends StatefulWidget {
  final List<dynamic> gridData;
  const DisciplineHistoryGrid({super.key, required this.gridData});

  @override
  State<DisciplineHistoryGrid> createState() => _DisciplineHistoryGridState();
}

class _DisciplineHistoryGridState extends State<DisciplineHistoryGrid> {
  final List<DataColumn> columns = [
    const DataColumn(label: Text('Matricula')),
    const DataColumn(label: Text('Ciclo')),
    const DataColumn(label: Text('Nombre del alumno')),
    const DataColumn(label: Text('Campus')),
    const DataColumn(label: Text('Grado')),
    const DataColumn(label: Text('Grupo')),
    const DataColumn(label: Text('Numero de empleado')),
    const DataColumn(label: Text('Nombre del maestro')),
    const DataColumn(label: Text('Hora')),
    const DataColumn(label: Text('Coordinadora')),
    const DataColumn(label: Text('Materia')),
  ];

  final List<DataRow> rows = [
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
    DataRow(cells: [
      DataCell(Text('999')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
      DataCell(Text('Activo')),
      DataCell(Text('1')),
      DataCell(Text('Juan Pérez')),
      DataCell(Text('2025-05-08')),
    ]),
  ];

  @override
  Widget build(BuildContext context) {
    final buttonsMenu = Padding(
      padding: const EdgeInsets.all(5),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                children: [Text('Buscador')],
              )
            ],
          ),
          Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  RefreshButton(onPressed: () {}),
                  SizedBox(
                    width: 5,
                  ),
                  EditItemButton(onPressed: () {})
                ],
              )
            ],
          )
        ],
      ),
    );

    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.all(10),
          child: buttonsMenu,
        ),
        const Divider(thickness: 2),
        Expanded(
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: DataTable(columns: columns, rows: rows),
              ),
            ),
          ),
        ),
      ],
    );
  }
}
