name: oxschool
description: Ox School.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.1
  data_table_2: ^2.5.15
  equatable: 2.0.5
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.1
  font_awesome_flutter: ^10.5.0
  from_css_color: 2.0.0
  go_router: ^14.4.1
  google_fonts: ^4.0.4
  intl: 0.19.0
  json_path: ^0.7.4
  mime_type: ^1.0.1
  page_transition: ^2.1.0
  path_provider: ^2.1.3
  path_provider_android: ^2.2.3
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.3.4
  # shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.2.1
  sqflite: ^2.3.2
  timeago: ^3.7.0
  url_launcher: ^6.1.14
  url_launcher_android: ^6.3.0
  url_launcher_ios: ^6.2.4
  url_launcher_platform_interface: ^2.3.2




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  pluto_grid: ^8.0.0
  device_info_plus: ^11.1.0
  flutter_expandable_fab: ^2.0.0
  loading_indicator: ^3.1.1
  multi_select_flutter: ^4.1.3
  requests: ^4.7.0
  flutter_spinkit: ^5.2.0
  #Set minimun size of screen
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  printing: ^5.11.1
  pdf: ^3.10.7
  get: ^4.6.6
  # pluto_grid_export: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  package_info_plus: ^8.1.2
  process_run: ^1.2.2+1
  install_plugin: ^2.1.0
  remove: ^1.0.10
  dio: ^5.8.0+1
  archive: ^4.0.4
      #ref: 927f8cbc09b35d85245c095f2db8f9b186f6618

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1 
  msix: ^3.16.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoRedondoOx.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logoRedondoOx.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logoRedondoOx.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logoRedondoOx.png"


msix_config:
  display_name: Ox School
  publisher_display_name: Ox School
  identity_name: oxschool.edu.mx
  #show_prompt: true
  logo_path: C:\oxAssets\logoRedondoOx.png
  capabilities: internetClient
  certificate_path: C:\oxschool.edu.mx.pfx
  certificate_password: M1S0J0SV3RD3S-
  publish_folder_path: C:\Users\erick\Desktop\oxReleases
  #sign_msix: false
  msix_version: 0.1yy.0.0

      



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/fonts/SoraFont/
    - assets/fonts/SoraFont/static/
    - lib/core/config/oxschool.env
 
  



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Sora
      fonts:
        - asset: assets/fonts/SoraFont/Sora-VariableFont_wght.ttf
        - asset: assets/fonts/SoraFont/static/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/SoraFont/static/Sora-Thin.ttf
          style: italic
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
